sudo: required
language: java
jdk:
- oraclejdk8
services:
 -docker
before_install: 
  - chmod +x ms-try/mvnw
  - chmod +x orchestration/mvnw
script: 
  - docker build -t parnalaskar/docker-mstest-img ./ms-try
  - docker build -t parnalaskar/docker-orchestration-img ./orchestration
after_script: 
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push parnalaskar/docker-mstest-img
  - docker push parnalaskar/docker-orchestration-img
