sudo: required
language: java
jdk:
- oraclejdk8
services:
 -docker
before_install: 
  - chmod +x orchestration/mvnw
script: 
  - docker build -t parna4laskar/docker-mstest-img ./ms-try
  - docker build -t parna4laskar/docker-orchestration-img ./orchestration
after_script: 
  - docker images
before-deploy:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push parna4laskar/docker-mstest-img
 - docker push parna4laskar/docker-orchestration-img


  